from vk_api.keyboard import VkKeyboard

kb_hello = VkKeyboard(one_time=True, inline=False)
kb_hello.add_button(label="Привет!", color='positive')

kb_main = VkKeyboard(one_time=True, inline=False)
kb_main.add_button(label="Искать пару", color='positive')
kb_main.add_button(label="Изменить параметры", color="primary")
kb_main.add_line()
kb_main.add_button(label="Пока", color='negative')

kb_params = VkKeyboard(one_time=False, inline=False)
kb_params.add_button(label="Искать пару", color='positive')
kb_params.add_line()
kb_params.add_button(label="Город", color="primary")
kb_params.add_button(label="Пол", color="primary")
kb_params.add_button(label="СП", color="primary")
kb_params.add_line()
kb_params.add_button(label="Мин. возраст", color="primary")
kb_params.add_button(label="Макс. возраст", color="primary")
kb_params.add_line()
kb_params.add_button(label="Пока", color='negative')

kb_search = VkKeyboard(one_time=False, inline=False)
kb_search.add_button(label="Следующий кандидат", color='positive')
kb_search.add_line()
kb_search.add_button(label="В избранное", color="primary")
kb_search.add_button(label="смотреть избранных", color="secondary")
kb_search.add_line()
kb_search.add_button(label="В черный список", color="primary")
kb_search.add_button(label="смотреть черный список", color="secondary")
kb_search.add_line()
kb_search.add_button(label="Изменить параметры", color="primary")
kb_search.add_button(label="Пока", color='negative')

kb_search_end_of_list = VkKeyboard(one_time=False, inline=False)
kb_search_end_of_list.add_button(label="Начать сначала", color='positive')
kb_search_end_of_list.add_line()
kb_search_end_of_list.add_button(label="В избранное", color="primary")
kb_search_end_of_list.add_button(label="смотреть избранных", color="secondary")
kb_search_end_of_list.add_line()
kb_search_end_of_list.add_button(label="В черный список", color="primary")
kb_search_end_of_list.add_button(label="смотреть черный список", color="secondary")
kb_search_end_of_list.add_line()
kb_search_end_of_list.add_button(label="Изменить параметры", color="primary")
kb_search_end_of_list.add_button(label="Пока", color='negative')

kb_back = VkKeyboard(one_time=False, inline=False)
kb_back.add_button(label="Назад", color="primary")
